create schema if not exists prazos;

create extension if not exists pgcrypto;

create table if not exists prazos.import_batches (
  id uuid primary key default gen_random_uuid(),
  source_type text not null check (source_type in ('CALCULO_MANUAL', 'PLANILHA_LOGISTICA', 'PLANILHA_VALIDADA')),
  source_name text null,
  file_name text null,
  validity_type text not null check (validity_type in ('PADRAO', 'PONTUAL')),
  valid_from date not null,
  valid_to date null,
  observation text null,
  payload jsonb null,
  created_at timestamptz not null default timezone('utc', now()),
  check (valid_to is null or valid_to >= valid_from)
);

create table if not exists prazos.route_versions (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references prazos.import_batches(id) on delete cascade,
  route_identity_key text not null,
  source_type text not null check (source_type in ('CALCULO_MANUAL', 'PLANILHA_LOGISTICA', 'PLANILHA_VALIDADA')),
  validity_type text not null check (validity_type in ('PADRAO', 'PONTUAL')),
  valid_from date not null,
  valid_to date null,
  observation text null,
  cd text not null,
  modal text not null,
  geography text not null,
  commercial_location text not null,
  locality text null,
  status text not null default 'ATIVO' check (status in ('ATIVO', 'ENCERRADO')),
  closed_at timestamptz null,
  closed_by_batch_id uuid null references prazos.import_batches(id),
  created_at timestamptz not null default timezone('utc', now()),
  check (valid_to is null or valid_to >= valid_from)
);

create table if not exists prazos.route_logic_events (
  id bigint generated by default as identity primary key,
  route_version_id uuid not null references prazos.route_versions(id) on delete cascade,
  event_order integer not null,
  route_destination text null,
  event_day text not null,
  cutoff_hour integer not null,
  delivery_day text not null,
  frequency text not null,
  raw_event jsonb null
);

create table if not exists prazos.deadline_rows (
  id bigint generated by default as identity primary key,
  route_version_id uuid not null references prazos.route_versions(id) on delete cascade,
  route_identity_key text not null,
  cd text not null,
  modal text not null,
  geography text not null,
  commercial_location text not null,
  locality text null,
  metodo_cd text not null default 'SUBSTITUIR',
  prazo_cd integer not null,
  metodo_tr text not null default 'SUBSTITUIR',
  prazo_tr integer not null,
  prazo_cliente integer not null,
  horario_inicial integer not null,
  horario_final integer not null,
  rota_fixa text not null,
  segunda boolean not null default false,
  terca boolean not null default false,
  quarta boolean not null default false,
  quinta boolean not null default false,
  sexta boolean not null default false,
  sabado boolean not null default false,
  domingo boolean not null default false,
  raw_row jsonb null
);

create table if not exists prazos.planning_batches (
  id uuid primary key default gen_random_uuid(),
  source_type text not null check (source_type in ('PLANEJAMENTO_MANUAL', 'PLANEJAMENTO_UPLOAD', 'AJUSTE_PONTUAL', 'AJUSTE_CD', 'AJUSTE_EMPRESA')),
  change_type text not null check (change_type in ('PADRAO', 'PONTUAL', 'FERIADO', 'PARALISACAO', 'DEMANDA', 'ALTERACAO_DEFINITIVA')),
  scope_type text not null default 'ROTA' check (scope_type in ('ROTA', 'ALINHAMENTO', 'CD', 'EMPRESA')),
  source_name text null,
  file_name text null,
  validity_type text not null check (validity_type in ('PADRAO', 'PONTUAL')),
  valid_from date not null,
  valid_to date null,
  observation text null,
  payload jsonb null,
  created_at timestamptz not null default timezone('utc', now()),
  check (valid_to is null or valid_to >= valid_from)
);

create table if not exists prazos.planning_route_versions (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references prazos.planning_batches(id) on delete cascade,
  route_identity_key text not null,
  source_type text not null check (source_type in ('PLANEJAMENTO_MANUAL', 'PLANEJAMENTO_UPLOAD', 'AJUSTE_PONTUAL', 'AJUSTE_CD', 'AJUSTE_EMPRESA')),
  change_type text not null check (change_type in ('PADRAO', 'PONTUAL', 'FERIADO', 'PARALISACAO', 'DEMANDA', 'ALTERACAO_DEFINITIVA')),
  scope_type text not null check (scope_type in ('ROTA', 'ALINHAMENTO', 'CD', 'EMPRESA')),
  validity_type text not null check (validity_type in ('PADRAO', 'PONTUAL')),
  valid_from date not null,
  valid_to date null,
  observation text null,
  cd text not null,
  modal text not null,
  geography text not null,
  commercial_location text not null,
  locality text null,
  route_destination text null,
  transport_plan text null,
  alignment_code text null,
  alignment_name text null,
  status text not null default 'ATIVO' check (status in ('ATIVO', 'ENCERRADO')),
  closed_at timestamptz null,
  closed_by_batch_id uuid null references prazos.planning_batches(id),
  created_at timestamptz not null default timezone('utc', now()),
  check (valid_to is null or valid_to >= valid_from)
);

create table if not exists prazos.planning_route_events (
  id bigint generated by default as identity primary key,
  planning_route_version_id uuid not null references prazos.planning_route_versions(id) on delete cascade,
  event_order integer not null,
  event_day text not null,
  cutoff_hour integer not null,
  delivery_day text not null,
  delivery_offered_day text null,
  frequency text not null,
  raw_event jsonb null
);

alter table prazos.import_batches
  add column if not exists planning_batch_id uuid null references prazos.planning_batches(id);

alter table prazos.route_versions
  add column if not exists planning_route_version_id uuid null references prazos.planning_route_versions(id);

create index if not exists import_batches_created_at_idx
  on prazos.import_batches (created_at desc);

create index if not exists route_versions_route_key_idx
  on prazos.route_versions (route_identity_key, valid_from desc, created_at desc);

create index if not exists route_versions_route_lookup_idx
  on prazos.route_versions (commercial_location, geography, modal, valid_from desc, created_at desc);

create index if not exists route_versions_validity_idx
  on prazos.route_versions (validity_type, valid_from, coalesce(valid_to, date '9999-12-31'));

create index if not exists deadline_rows_route_version_idx
  on prazos.deadline_rows (route_version_id);

create index if not exists deadline_rows_route_key_idx
  on prazos.deadline_rows (route_identity_key, commercial_location, geography, modal);

create index if not exists planning_batches_created_at_idx
  on prazos.planning_batches (created_at desc);

create index if not exists planning_route_versions_route_key_idx
  on prazos.planning_route_versions (route_identity_key, valid_from desc, created_at desc);

create index if not exists planning_route_versions_lookup_idx
  on prazos.planning_route_versions (commercial_location, geography, modal, valid_from desc, created_at desc);

create index if not exists planning_route_versions_alignment_idx
  on prazos.planning_route_versions (alignment_code, cd, valid_from desc);

create index if not exists planning_route_events_version_idx
  on prazos.planning_route_events (planning_route_version_id, event_order);

grant usage on schema prazos to service_role;
grant all privileges on all tables in schema prazos to service_role;
grant all privileges on all sequences in schema prazos to service_role;
alter default privileges in schema prazos grant all privileges on tables to service_role;
alter default privileges in schema prazos grant all privileges on sequences to service_role;

create or replace function public.prazos_apply_dataset(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, prazos
as $$
declare
  v_batch_id uuid;
  v_valid_from date;
  v_valid_to date;
  v_validity_type text;
  v_source_type text;
  v_route_payload jsonb;
  v_route_version_id uuid;
  v_route_identity_key text;
  v_route_count integer := 0;
  v_row_count integer := 0;
begin
  if p_payload is null then
    raise exception 'Payload de persistencia nao enviado.';
  end if;

  v_valid_from := (p_payload ->> 'valid_from')::date;
  v_valid_to := nullif(p_payload ->> 'valid_to', '')::date;
  v_validity_type := upper(coalesce(p_payload ->> 'validity_type', ''));
  v_source_type := upper(coalesce(p_payload ->> 'source_type', ''));

  if v_validity_type not in ('PADRAO', 'PONTUAL') then
    raise exception 'Tipo de vigencia invalido: %', v_validity_type;
  end if;

  if v_source_type not in ('CALCULO_MANUAL', 'PLANILHA_LOGISTICA', 'PLANILHA_VALIDADA') then
    raise exception 'Tipo de origem invalido: %', v_source_type;
  end if;

  if v_valid_from is null then
    raise exception 'Data inicial de vigencia obrigatoria.';
  end if;

  if v_validity_type = 'PONTUAL' and v_valid_to is null then
    raise exception 'Para vigencia pontual, informe a data final.';
  end if;

  if v_valid_to is not null and v_valid_to < v_valid_from then
    raise exception 'A data final nao pode ser anterior a data inicial.';
  end if;

  insert into prazos.import_batches (
    source_type,
    source_name,
    file_name,
    validity_type,
    valid_from,
    valid_to,
    observation,
    payload,
    planning_batch_id
  )
  values (
    v_source_type,
    nullif(p_payload ->> 'source_name', ''),
    nullif(p_payload ->> 'file_name', ''),
    v_validity_type,
    v_valid_from,
    v_valid_to,
    nullif(p_payload ->> 'observation', ''),
    p_payload -> 'payload',
    nullif(p_payload ->> 'planning_batch_id', '')::uuid
  )
  returning id into v_batch_id;

  for v_route_payload in
    select value
    from jsonb_array_elements(coalesce(p_payload -> 'route_versions', '[]'::jsonb))
  loop
    v_route_identity_key := coalesce(v_route_payload ->> 'route_identity_key', '');

    if v_route_identity_key = '' then
      raise exception 'Rota sem chave de identidade enviada para persistencia.';
    end if;

    if v_validity_type = 'PADRAO' then
      if exists (
        select 1
        from prazos.route_versions existing_version
        where existing_version.route_identity_key = v_route_identity_key
          and existing_version.validity_type = 'PADRAO'
          and existing_version.valid_from > v_valid_from
          and coalesce(existing_version.valid_to, date '9999-12-31') >= v_valid_from
      ) then
        raise exception 'Ja existe um prazo PADRAO futuro ou sobreposto para a rota % a partir de %.', v_route_identity_key, v_valid_from;
      end if;

      update prazos.route_versions
      set
        valid_to = case when valid_from = v_valid_from then v_valid_from else v_valid_from - 1 end,
        status = 'ENCERRADO',
        closed_at = timezone('utc', now()),
        closed_by_batch_id = v_batch_id
      where route_identity_key = v_route_identity_key
        and validity_type = 'PADRAO'
        and (
          (valid_from < v_valid_from and coalesce(valid_to, date '9999-12-31') >= v_valid_from)
          or valid_from = v_valid_from
        );
    else
      if exists (
        select 1
        from prazos.route_versions existing_version
        where existing_version.route_identity_key = v_route_identity_key
          and existing_version.validity_type = 'PONTUAL'
          and daterange(existing_version.valid_from, coalesce(existing_version.valid_to, existing_version.valid_from), '[]')
              && daterange(v_valid_from, coalesce(v_valid_to, v_valid_from), '[]')
      ) then
        raise exception 'Ja existe uma vigencia PONTUAL sobreposta para a rota % no periodo informado.', v_route_identity_key;
      end if;
    end if;

    insert into prazos.route_versions (
      batch_id,
      route_identity_key,
      source_type,
      validity_type,
      valid_from,
      valid_to,
      observation,
      cd,
      modal,
      geography,
      commercial_location,
      locality,
      planning_route_version_id
    )
    values (
      v_batch_id,
      v_route_identity_key,
      v_source_type,
      v_validity_type,
      v_valid_from,
      v_valid_to,
      nullif(p_payload ->> 'observation', ''),
      coalesce(v_route_payload ->> 'cd', ''),
      coalesce(v_route_payload ->> 'modal', ''),
      coalesce(v_route_payload ->> 'geography', ''),
      coalesce(v_route_payload ->> 'commercial_location', ''),
      nullif(v_route_payload ->> 'locality', ''),
      nullif(v_route_payload ->> 'planning_route_version_id', '')::uuid
    )
    returning id into v_route_version_id;

    insert into prazos.route_logic_events (
      route_version_id,
      event_order,
      route_destination,
      event_day,
      cutoff_hour,
      delivery_day,
      frequency,
      raw_event
    )
    select
      v_route_version_id,
      coalesce((logic_event ->> 'event_order')::integer, logic_index::integer),
      nullif(logic_event ->> 'route_destination', ''),
      coalesce(logic_event ->> 'event_day', ''),
      coalesce((logic_event ->> 'cutoff_hour')::integer, 0),
      coalesce(logic_event ->> 'delivery_day', ''),
      coalesce(logic_event ->> 'frequency', 'SEMANAL'),
      logic_event -> 'raw_event'
    from jsonb_array_elements(coalesce(v_route_payload -> 'logic_events', '[]'::jsonb))
      with ordinality as logic_events(logic_event, logic_index);

    insert into prazos.deadline_rows (
      route_version_id,
      route_identity_key,
      cd,
      modal,
      geography,
      commercial_location,
      locality,
      metodo_cd,
      prazo_cd,
      metodo_tr,
      prazo_tr,
      prazo_cliente,
      horario_inicial,
      horario_final,
      rota_fixa,
      segunda,
      terca,
      quarta,
      quinta,
      sexta,
      sabado,
      domingo,
      raw_row
    )
    select
      v_route_version_id,
      v_route_identity_key,
      coalesce(deadline_row ->> 'cd', ''),
      coalesce(deadline_row ->> 'modal', ''),
      coalesce(deadline_row ->> 'geography', ''),
      coalesce(deadline_row ->> 'commercial_location', ''),
      nullif(deadline_row ->> 'locality', ''),
      coalesce(deadline_row ->> 'metodo_cd', 'SUBSTITUIR'),
      coalesce((deadline_row ->> 'prazo_cd')::integer, 0),
      coalesce(deadline_row ->> 'metodo_tr', 'SUBSTITUIR'),
      coalesce((deadline_row ->> 'prazo_tr')::integer, 0),
      coalesce((deadline_row ->> 'prazo_cliente')::integer, 0),
      coalesce((deadline_row ->> 'horario_inicial')::integer, 0),
      coalesce((deadline_row ->> 'horario_final')::integer, 0),
      coalesce(deadline_row ->> 'rota_fixa', 'NAO'),
      coalesce((deadline_row ->> 'segunda')::boolean, false),
      coalesce((deadline_row ->> 'terca')::boolean, false),
      coalesce((deadline_row ->> 'quarta')::boolean, false),
      coalesce((deadline_row ->> 'quinta')::boolean, false),
      coalesce((deadline_row ->> 'sexta')::boolean, false),
      coalesce((deadline_row ->> 'sabado')::boolean, false),
      coalesce((deadline_row ->> 'domingo')::boolean, false),
      deadline_row -> 'raw_row'
    from jsonb_array_elements(coalesce(v_route_payload -> 'rows', '[]'::jsonb)) as deadline_rows(deadline_row);

    v_route_count := v_route_count + 1;
    v_row_count := v_row_count + coalesce(jsonb_array_length(v_route_payload -> 'rows'), 0);
  end loop;

  return jsonb_build_object(
    'batch_id', v_batch_id,
    'route_versions', v_route_count,
    'deadline_rows', v_row_count,
    'validity_type', v_validity_type,
    'valid_from', v_valid_from,
    'valid_to', v_valid_to
  );
end;
$$;

drop function if exists public.prazos_get_valid_rows(date, text, text, text);

create function public.prazos_get_valid_rows(
  p_reference_date date,
  p_commercial_location text,
  p_geography text default null,
  p_modal text default null
)
returns table (
  route_version_id uuid,
  batch_id uuid,
  source_type text,
  validity_type text,
  valid_from date,
  valid_to date,
  observation text,
  created_at timestamptz,
  cd text,
  modal text,
  geography text,
  commercial_location text,
  locality text,
  metodo_cd text,
  prazo_cd integer,
  metodo_tr text,
  prazo_tr integer,
  prazo_cliente integer,
  horario_inicial integer,
  horario_final integer,
  rota_fixa text,
  segunda text,
  terca text,
  quarta text,
  quinta text,
  sexta text,
  sabado text,
  domingo text,
  raw_row jsonb
)
language sql
security definer
set search_path = public, prazos
as $$
  with candidate_versions as (
    select
      route_version.*,
      row_number() over (
        partition by route_version.route_identity_key
        order by
          case route_version.validity_type when 'PONTUAL' then 0 else 1 end,
          route_version.valid_from desc,
          route_version.created_at desc
      ) as rn
    from prazos.route_versions as route_version
    where route_version.valid_from <= p_reference_date
      and coalesce(route_version.valid_to, date '9999-12-31') >= p_reference_date
      and route_version.commercial_location = p_commercial_location
      and (p_geography is null or route_version.geography = p_geography)
      and (p_modal is null or route_version.modal = p_modal)
  )
  select
    candidate_version.id as route_version_id,
    candidate_version.batch_id,
    candidate_version.source_type,
    candidate_version.validity_type,
    candidate_version.valid_from,
    candidate_version.valid_to,
    candidate_version.observation,
    candidate_version.created_at,
    deadline_row.cd,
    deadline_row.modal,
    deadline_row.geography,
    deadline_row.commercial_location,
    deadline_row.locality,
    deadline_row.metodo_cd,
    deadline_row.prazo_cd,
    deadline_row.metodo_tr,
    deadline_row.prazo_tr,
    deadline_row.prazo_cliente,
    deadline_row.horario_inicial,
    deadline_row.horario_final,
    deadline_row.rota_fixa,
    case when deadline_row.segunda then 'OK' else 'NOK' end as segunda,
    case when deadline_row.terca then 'OK' else 'NOK' end as terca,
    case when deadline_row.quarta then 'OK' else 'NOK' end as quarta,
    case when deadline_row.quinta then 'OK' else 'NOK' end as quinta,
    case when deadline_row.sexta then 'OK' else 'NOK' end as sexta,
    case when deadline_row.sabado then 'OK' else 'NOK' end as sabado,
    case when deadline_row.domingo then 'OK' else 'NOK' end as domingo,
    deadline_row.raw_row
  from candidate_versions as candidate_version
  join prazos.deadline_rows as deadline_row
    on deadline_row.route_version_id = candidate_version.id
  where candidate_version.rn = 1
  order by
    deadline_row.commercial_location,
    deadline_row.geography,
    deadline_row.modal,
    deadline_row.horario_inicial,
    deadline_row.horario_final;
$$;

create or replace function public.prazos_get_version_history(
  p_commercial_location text,
  p_geography text default null,
  p_modal text default null
)
returns table (
  route_version_id uuid,
  batch_id uuid,
  route_identity_key text,
  source_type text,
  validity_type text,
  valid_from date,
  valid_to date,
  status text,
  observation text,
  created_at timestamptz,
  row_count bigint
)
language sql
security definer
set search_path = public, prazos
as $$
  select
    route_version.id as route_version_id,
    route_version.batch_id,
    route_version.route_identity_key,
    route_version.source_type,
    route_version.validity_type,
    route_version.valid_from,
    route_version.valid_to,
    route_version.status,
    route_version.observation,
    route_version.created_at,
    count(deadline_row.id) as row_count
  from prazos.route_versions as route_version
  left join prazos.deadline_rows as deadline_row
    on deadline_row.route_version_id = route_version.id
  where route_version.commercial_location = p_commercial_location
    and (p_geography is null or route_version.geography = p_geography)
    and (p_modal is null or route_version.modal = p_modal)
  group by route_version.id
  order by route_version.valid_from desc, route_version.created_at desc;
$$;

create or replace function public.prazos_apply_planning_dataset(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, prazos
as $$
declare
  v_planning_batch_id uuid;
  v_valid_from date;
  v_valid_to date;
  v_validity_type text;
  v_source_type text;
  v_change_type text;
  v_scope_type text;
  v_deadline_source_type text;
  v_route_payload jsonb;
  v_planning_route_version_id uuid;
  v_route_identity_key text;
  v_route_count integer := 0;
  v_event_count integer := 0;
  v_deadline_route_versions jsonb := '[]'::jsonb;
  v_deadline_payload jsonb;
  v_deadline_result jsonb;
begin
  if p_payload is null then
    raise exception 'Payload de planejamento nao enviado.';
  end if;

  v_valid_from := (p_payload ->> 'valid_from')::date;
  v_valid_to := nullif(p_payload ->> 'valid_to', '')::date;
  v_validity_type := upper(coalesce(p_payload ->> 'validity_type', ''));
  v_source_type := upper(coalesce(p_payload ->> 'source_type', 'PLANEJAMENTO_UPLOAD'));
  v_change_type := upper(coalesce(p_payload ->> 'change_type', v_validity_type));
  v_scope_type := upper(coalesce(p_payload ->> 'scope_type', 'ROTA'));
  v_deadline_source_type := upper(coalesce(p_payload ->> 'deadline_source_type', 'PLANILHA_LOGISTICA'));

  if v_validity_type not in ('PADRAO', 'PONTUAL') then
    raise exception 'Tipo de vigencia invalido: %', v_validity_type;
  end if;

  if v_source_type not in ('PLANEJAMENTO_MANUAL', 'PLANEJAMENTO_UPLOAD', 'AJUSTE_PONTUAL', 'AJUSTE_CD', 'AJUSTE_EMPRESA') then
    raise exception 'Tipo de origem do planejamento invalido: %', v_source_type;
  end if;

  if v_change_type not in ('PADRAO', 'PONTUAL', 'FERIADO', 'PARALISACAO', 'DEMANDA', 'ALTERACAO_DEFINITIVA') then
    raise exception 'Tipo de ajuste do planejamento invalido: %', v_change_type;
  end if;

  if v_scope_type not in ('ROTA', 'ALINHAMENTO', 'CD', 'EMPRESA') then
    raise exception 'Escopo do planejamento invalido: %', v_scope_type;
  end if;

  if v_deadline_source_type not in ('CALCULO_MANUAL', 'PLANILHA_LOGISTICA', 'PLANILHA_VALIDADA') then
    raise exception 'Tipo de origem do prazo invalido: %', v_deadline_source_type;
  end if;

  if v_valid_from is null then
    raise exception 'Data inicial de vigencia obrigatoria.';
  end if;

  if v_validity_type = 'PONTUAL' and v_valid_to is null then
    raise exception 'Para vigencia pontual, informe a data final.';
  end if;

  if v_valid_to is not null and v_valid_to < v_valid_from then
    raise exception 'A data final nao pode ser anterior a data inicial.';
  end if;

  insert into prazos.planning_batches (
    source_type,
    change_type,
    scope_type,
    source_name,
    file_name,
    validity_type,
    valid_from,
    valid_to,
    observation,
    payload
  )
  values (
    v_source_type,
    v_change_type,
    v_scope_type,
    nullif(p_payload ->> 'source_name', ''),
    nullif(p_payload ->> 'file_name', ''),
    v_validity_type,
    v_valid_from,
    v_valid_to,
    nullif(p_payload ->> 'observation', ''),
    p_payload -> 'payload'
  )
  returning id into v_planning_batch_id;

  for v_route_payload in
    select value
    from jsonb_array_elements(coalesce(p_payload -> 'route_versions', '[]'::jsonb))
  loop
    v_route_identity_key := coalesce(v_route_payload ->> 'route_identity_key', '');

    if v_route_identity_key = '' then
      raise exception 'Rota sem chave de identidade enviada para persistencia do planejamento.';
    end if;

    if v_validity_type = 'PADRAO' then
      if exists (
        select 1
        from prazos.planning_route_versions existing_version
        where existing_version.route_identity_key = v_route_identity_key
          and existing_version.validity_type = 'PADRAO'
          and existing_version.valid_from > v_valid_from
          and coalesce(existing_version.valid_to, date '9999-12-31') >= v_valid_from
      ) then
        raise exception 'Ja existe um planejamento PADRAO futuro ou sobreposto para a rota % a partir de %.', v_route_identity_key, v_valid_from;
      end if;

      update prazos.planning_route_versions
      set
        valid_to = case when valid_from = v_valid_from then v_valid_from else v_valid_from - 1 end,
        status = 'ENCERRADO',
        closed_at = timezone('utc', now()),
        closed_by_batch_id = v_planning_batch_id
      where route_identity_key = v_route_identity_key
        and validity_type = 'PADRAO'
        and (
          (valid_from < v_valid_from and coalesce(valid_to, date '9999-12-31') >= v_valid_from)
          or valid_from = v_valid_from
        );
    else
      if exists (
        select 1
        from prazos.planning_route_versions existing_version
        where existing_version.route_identity_key = v_route_identity_key
          and existing_version.validity_type = 'PONTUAL'
          and daterange(existing_version.valid_from, coalesce(existing_version.valid_to, existing_version.valid_from), '[]')
              && daterange(v_valid_from, coalesce(v_valid_to, v_valid_from), '[]')
      ) then
        raise exception 'Ja existe um planejamento PONTUAL sobreposto para a rota % no periodo informado.', v_route_identity_key;
      end if;
    end if;

    insert into prazos.planning_route_versions (
      batch_id,
      route_identity_key,
      source_type,
      change_type,
      scope_type,
      validity_type,
      valid_from,
      valid_to,
      observation,
      cd,
      modal,
      geography,
      commercial_location,
      locality,
      route_destination,
      transport_plan,
      alignment_code,
      alignment_name
    )
    values (
      v_planning_batch_id,
      v_route_identity_key,
      v_source_type,
      v_change_type,
      v_scope_type,
      v_validity_type,
      v_valid_from,
      v_valid_to,
      nullif(p_payload ->> 'observation', ''),
      coalesce(v_route_payload ->> 'cd', ''),
      coalesce(v_route_payload ->> 'modal', ''),
      coalesce(v_route_payload ->> 'geography', ''),
      coalesce(v_route_payload ->> 'commercial_location', ''),
      nullif(v_route_payload ->> 'locality', ''),
      nullif(v_route_payload ->> 'route_destination', ''),
      nullif(v_route_payload ->> 'transport_plan', ''),
      nullif(v_route_payload ->> 'alignment_code', ''),
      nullif(v_route_payload ->> 'alignment_name', '')
    )
    returning id into v_planning_route_version_id;

    insert into prazos.planning_route_events (
      planning_route_version_id,
      event_order,
      event_day,
      cutoff_hour,
      delivery_day,
      delivery_offered_day,
      frequency,
      raw_event
    )
    select
      v_planning_route_version_id,
      coalesce((logic_event ->> 'event_order')::integer, logic_index::integer),
      coalesce(logic_event ->> 'event_day', ''),
      coalesce((logic_event ->> 'cutoff_hour')::integer, 0),
      coalesce(logic_event ->> 'delivery_day', ''),
      nullif(logic_event ->> 'delivery_offered_day', ''),
      coalesce(logic_event ->> 'frequency', 'SEMANAL'),
      logic_event -> 'raw_event'
    from jsonb_array_elements(coalesce(v_route_payload -> 'logic_events', '[]'::jsonb))
      with ordinality as logic_events(logic_event, logic_index);

    v_route_count := v_route_count + 1;
    v_event_count := v_event_count + coalesce(jsonb_array_length(v_route_payload -> 'logic_events'), 0);

    v_deadline_route_versions := v_deadline_route_versions || jsonb_build_array(
      jsonb_build_object(
        'route_identity_key', v_route_identity_key,
        'cd', coalesce(v_route_payload ->> 'cd', ''),
        'modal', coalesce(v_route_payload ->> 'modal', ''),
        'geography', coalesce(v_route_payload ->> 'geography', ''),
        'commercial_location', coalesce(v_route_payload ->> 'commercial_location', ''),
        'locality', nullif(v_route_payload ->> 'locality', ''),
        'planning_route_version_id', v_planning_route_version_id,
        'logic_events', coalesce(v_route_payload -> 'logic_events', '[]'::jsonb),
        'rows', coalesce(v_route_payload -> 'rows', '[]'::jsonb)
      )
    );
  end loop;

  v_deadline_payload := jsonb_build_object(
    'source_type', v_deadline_source_type,
    'source_name', coalesce(p_payload ->> 'source_name', ''),
    'file_name', coalesce(p_payload ->> 'file_name', ''),
    'validity_type', v_validity_type,
    'valid_from', v_valid_from,
    'valid_to', v_valid_to,
    'observation', coalesce(p_payload ->> 'observation', ''),
    'payload', coalesce(p_payload -> 'payload', 'null'::jsonb),
    'planning_batch_id', v_planning_batch_id,
    'route_versions', v_deadline_route_versions
  );

  v_deadline_result := public.prazos_apply_dataset(v_deadline_payload);

  return jsonb_build_object(
    'planning_batch_id', v_planning_batch_id,
    'deadline_batch_id', v_deadline_result ->> 'batch_id',
    'planning_route_versions', v_route_count,
    'planning_events', v_event_count,
    'deadline_route_versions', coalesce((v_deadline_result ->> 'route_versions')::integer, 0),
    'deadline_rows', coalesce((v_deadline_result ->> 'deadline_rows')::integer, 0),
    'validity_type', v_validity_type,
    'valid_from', v_valid_from,
    'valid_to', v_valid_to
  );
end;
$$;

create or replace function public.prazos_get_valid_planning(
  p_reference_date date,
  p_commercial_location text,
  p_geography text default null,
  p_modal text default null
)
returns table (
  planning_route_version_id uuid,
  planning_batch_id uuid,
  source_type text,
  change_type text,
  scope_type text,
  validity_type text,
  valid_from date,
  valid_to date,
  observation text,
  created_at timestamptz,
  cd text,
  modal text,
  geography text,
  commercial_location text,
  locality text,
  route_destination text,
  transport_plan text,
  alignment_code text,
  alignment_name text,
  event_order integer,
  event_day text,
  cutoff_hour integer,
  delivery_day text,
  delivery_offered_day text,
  frequency text
)
language sql
security definer
set search_path = public, prazos
as $$
  with candidate_versions as (
    select
      planning_version.*,
      row_number() over (
        partition by planning_version.route_identity_key
        order by
          case planning_version.validity_type when 'PONTUAL' then 0 else 1 end,
          planning_version.valid_from desc,
          planning_version.created_at desc
      ) as rn
    from prazos.planning_route_versions as planning_version
    where planning_version.valid_from <= p_reference_date
      and coalesce(planning_version.valid_to, date '9999-12-31') >= p_reference_date
      and planning_version.commercial_location = p_commercial_location
      and (p_geography is null or planning_version.geography = p_geography)
      and (p_modal is null or planning_version.modal = p_modal)
  )
  select
    candidate_version.id as planning_route_version_id,
    candidate_version.batch_id as planning_batch_id,
    candidate_version.source_type,
    candidate_version.change_type,
    candidate_version.scope_type,
    candidate_version.validity_type,
    candidate_version.valid_from,
    candidate_version.valid_to,
    candidate_version.observation,
    candidate_version.created_at,
    candidate_version.cd,
    candidate_version.modal,
    candidate_version.geography,
    candidate_version.commercial_location,
    candidate_version.locality,
    candidate_version.route_destination,
    candidate_version.transport_plan,
    candidate_version.alignment_code,
    candidate_version.alignment_name,
    planning_event.event_order,
    planning_event.event_day,
    planning_event.cutoff_hour,
    planning_event.delivery_day,
    planning_event.delivery_offered_day,
    planning_event.frequency
  from candidate_versions as candidate_version
  join prazos.planning_route_events as planning_event
    on planning_event.planning_route_version_id = candidate_version.id
  where candidate_version.rn = 1
  order by
    candidate_version.commercial_location,
    candidate_version.geography,
    candidate_version.modal,
    planning_event.event_order;
$$;

create or replace function public.prazos_get_planning_history(
  p_commercial_location text,
  p_geography text default null,
  p_modal text default null
)
returns table (
  planning_route_version_id uuid,
  planning_batch_id uuid,
  route_identity_key text,
  source_type text,
  change_type text,
  scope_type text,
  validity_type text,
  valid_from date,
  valid_to date,
  status text,
  observation text,
  created_at timestamptz,
  cd text,
  modal text,
  geography text,
  commercial_location text,
  locality text,
  route_destination text,
  transport_plan text,
  alignment_code text,
  alignment_name text,
  event_count bigint
)
language sql
security definer
set search_path = public, prazos
as $$
  select
    planning_version.id as planning_route_version_id,
    planning_version.batch_id as planning_batch_id,
    planning_version.route_identity_key,
    planning_version.source_type,
    planning_version.change_type,
    planning_version.scope_type,
    planning_version.validity_type,
    planning_version.valid_from,
    planning_version.valid_to,
    planning_version.status,
    planning_version.observation,
    planning_version.created_at,
    planning_version.cd,
    planning_version.modal,
    planning_version.geography,
    planning_version.commercial_location,
    planning_version.locality,
    planning_version.route_destination,
    planning_version.transport_plan,
    planning_version.alignment_code,
    planning_version.alignment_name,
    count(planning_event.id) as event_count
  from prazos.planning_route_versions as planning_version
  left join prazos.planning_route_events as planning_event
    on planning_event.planning_route_version_id = planning_version.id
  where planning_version.commercial_location = p_commercial_location
    and (p_geography is null or planning_version.geography = p_geography)
    and (p_modal is null or planning_version.modal = p_modal)
  group by planning_version.id
  order by planning_version.valid_from desc, planning_version.created_at desc;
$$;

create or replace function public.prazos_get_rows_by_route_version(
  p_route_version_id uuid
)
returns table (
  route_version_id uuid,
  batch_id uuid,
  planning_route_version_id uuid,
  source_type text,
  validity_type text,
  valid_from date,
  valid_to date,
  observation text,
  created_at timestamptz,
  cd text,
  modal text,
  geography text,
  commercial_location text,
  locality text,
  metodo_cd text,
  prazo_cd integer,
  metodo_tr text,
  prazo_tr integer,
  prazo_cliente integer,
  horario_inicial integer,
  horario_final integer,
  rota_fixa text,
  segunda text,
  terca text,
  quarta text,
  quinta text,
  sexta text,
  sabado text,
  domingo text,
  raw_row jsonb
)
language sql
security definer
set search_path = public, prazos
as $$
  select
    route_version.id as route_version_id,
    route_version.batch_id,
    route_version.planning_route_version_id,
    route_version.source_type,
    route_version.validity_type,
    route_version.valid_from,
    route_version.valid_to,
    route_version.observation,
    route_version.created_at,
    deadline_row.cd,
    deadline_row.modal,
    deadline_row.geography,
    deadline_row.commercial_location,
    deadline_row.locality,
    deadline_row.metodo_cd,
    deadline_row.prazo_cd,
    deadline_row.metodo_tr,
    deadline_row.prazo_tr,
    deadline_row.prazo_cliente,
    deadline_row.horario_inicial,
    deadline_row.horario_final,
    deadline_row.rota_fixa,
    case when deadline_row.segunda then 'OK' else 'NOK' end as segunda,
    case when deadline_row.terca then 'OK' else 'NOK' end as terca,
    case when deadline_row.quarta then 'OK' else 'NOK' end as quarta,
    case when deadline_row.quinta then 'OK' else 'NOK' end as quinta,
    case when deadline_row.sexta then 'OK' else 'NOK' end as sexta,
    case when deadline_row.sabado then 'OK' else 'NOK' end as sabado,
    case when deadline_row.domingo then 'OK' else 'NOK' end as domingo,
    deadline_row.raw_row
  from prazos.route_versions as route_version
  join prazos.deadline_rows as deadline_row
    on deadline_row.route_version_id = route_version.id
  where route_version.id = p_route_version_id
  order by deadline_row.commercial_location, deadline_row.geography, deadline_row.modal, deadline_row.horario_inicial, deadline_row.horario_final;
$$;

revoke all on function public.prazos_apply_dataset(jsonb) from public;
revoke all on function public.prazos_apply_planning_dataset(jsonb) from public;
revoke all on function public.prazos_get_valid_rows(date, text, text, text) from public;
revoke all on function public.prazos_get_version_history(text, text, text) from public;
revoke all on function public.prazos_get_valid_planning(date, text, text, text) from public;
revoke all on function public.prazos_get_planning_history(text, text, text) from public;
revoke all on function public.prazos_get_rows_by_route_version(uuid) from public;

grant execute on function public.prazos_apply_dataset(jsonb) to service_role;
grant execute on function public.prazos_apply_planning_dataset(jsonb) to service_role;
grant execute on function public.prazos_get_valid_rows(date, text, text, text) to service_role;
grant execute on function public.prazos_get_version_history(text, text, text) to service_role;
grant execute on function public.prazos_get_valid_planning(date, text, text, text) to service_role;
grant execute on function public.prazos_get_planning_history(text, text, text) to service_role;
grant execute on function public.prazos_get_rows_by_route_version(uuid) to service_role;
